# Suspicious PDF Producers / Editors indicating post-generation manipulation or online redaction
producers:
  - "Photoshop"
  - "Adobe Photoshop"
  - "Canva"
  - "iLovePDF"
  - "ilovepdf"
  - "Sejda"
  - "Smallpdf"
  - "smallpdf"
  - "PDFescape"
  - "Nitro"
  - "Nitro Pro"
  - "Foxit"
  - "Foxit PhantomPDF"
  - "Master PDF Editor"
  - "Inkscape"
  - "GIMP"
  - "Acrobat Distiller"
  - "PDF24"
  - "PDF Creator"
  - "Wondershare PDFelement"
  - "PDF Editor"
  - "LibreOffice"
  - "PDF Architect"
